# Generated by Django 4.1.7 on 2023-04-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=50, verbose_name='Бренд машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=50, verbose_name='Год выпуска'),
        ),
    ]
